//JAVASCRIPT EXECUTION CONTEXT...=>USE TO DETERMINE ,HOW JS CODE EXECUTES

//______3 WAYS OF EXECUTION CONTEXT,MAIN AR FIRST TWO
//1. GLOBAL EXECUTION CONTEXT(GEC)
//2. FUNCTIONAL EXECUTION CONTEXT 
//3. EVAL EXECUTION CONTEXT (NOT SO IMPORTANT )

//---------------GLOBAL EXECUTION CONTEXT--------------
//{} this KEYWORD USE TO STORE (GEC)=> EXECUTES IN 2 PHASE 
//1. MEMORY CREATION PHASE(WHATEVER VARIABLE WE CREATED IT ,IT WILL ONLY GET ALLOCATED IN MEMORY,NOT EXECUTE)
//2.EXECUTION PHASE(EXECUTES TASK,ASSIGN VALUES TO VARIABLE)

